FROM ubuntu:xenial
MAINTAINER Ingo Müller <ingo.mueller@inf.ethz.ch>

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        binutils-dev \
        cmake \
        ninja-build \
        libstdc++-5-dev \
        python-minimal \
        wget \
        xz-utils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir /opt/clang+llvm-6.0.1/ && \
    cd /opt/clang+llvm-6.0.1/ && \
    wget http://releases.llvm.org/6.0.1/clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz -O - \
         | tar -x -I xz --strip-components=1 && \
    for file in bin/*; \
    do \
        ln -s $PWD/$file /usr/bin/$(basename $file)-6.0; \
    done

RUN cd /tmp/ && \
    wget http://releases.llvm.org/6.0.1/llvm-6.0.1.src.tar.xz && \
    tar -xf llvm-6.0.1.src.tar.xz && \
    mkdir /tmp/llvm-6.0.1.src/build && \
    cd /tmp/llvm-6.0.1.src/build && \
    CXX=clang++-6.0 CC=clang-6.0 cmake -G Ninja ../ \
        -DLLVM_BINUTILS_INCDIR=/usr/include \
        -DLLVM_TARGETS_TO_BUILD=X86 \
        -DCMAKE_BUILD_TYPE=MinSizeRel \
        -DLLVM_OPTIMIZED_TABLEGEN=ON && \
    ninja lib/libLLVMDemangle.a \
        lib/libLLVMSupport.a \
        lib/libLLVMTableGen.a \
        bin/llvm-tblgen \
        lib/libLLVMCore.a \
        lib/libLLVMIRReader.a \
        lib/libLLVMCodeGen.a \
        lib/libLLVMSelectionDAG.a \
        lib/libLLVMAsmPrinter.a \
        lib/libLLVMBinaryFormat.a \
        lib/libLLVMGlobalISel.a \
        lib/libLLVMBitReader.a \
        lib/libLLVMBitWriter.a \
        lib/libLLVMTransformUtils.a \
        lib/libLLVMInstrumentation.a \
        lib/libLLVMInstCombine.a 
