FROM ubuntu:focal
MAINTAINER Ingo Müller <ingo.mueller@inf.ethz.ch>

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        binutils-dev \
        cmake \
        ninja-build \
        libstdc++-10-dev \
        libtinfo5 \
        python3-minimal \
        wget \
        xz-utils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir /opt/clang+llvm-11.0.0/ && \
    cd /opt/clang+llvm-11.0.0/ && \
    wget --progress=dot:giga https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz -O - \
         | tar -x -I xz --strip-components=1 && \
    for file in bin/*; \
    do \
        ln -s $PWD/$file /usr/bin/$(basename $file)-11.0; \
    done && \
    cp /opt/clang+llvm-11.0.0/lib/libomp.so /opt/clang+llvm-11.0.0/lib/libomp.so.5

RUN cd /tmp/ && \
    wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/llvm-11.0.0.src.tar.xz && \
    tar -xf llvm-11.0.0.src.tar.xz && \
    mkdir /tmp/llvm-11.0.0.src/build && \
    cd /tmp/llvm-11.0.0.src/build && \
    CXX=clang++-11.0 CC=clang-11.0 cmake -G Ninja ../ \
        -DLLVM_BINUTILS_INCDIR=/usr/include \
        -DLLVM_TARGETS_TO_BUILD=X86 \
        -DCMAKE_BUILD_TYPE=MinSizeRel \
        -DLLVM_OPTIMIZED_TABLEGEN=ON && \
    ninja LLVMgold
